version: 2
sources:
  - name: raw
    database: DBT_LAB
    schema: raw
    tables:
      - name: table_001
      - name: table_002
      - name: table_003
      - name: table_004
      - name: table_005
      - name: table_006
      - name: table_007
      - name: table_008
      - name: table_009
      - name: table_010
      - name: table_011
      - name: table_012
      - name: table_013
      - name: table_014
      - name: table_015
      - name: table_016
      - name: table_017
      - name: table_018
      - name: table_019
      - name: table_020
      - name: table_021
      - name: table_022
      - name: table_023
      - name: table_024
      - name: table_025
      - name: table_026
      - name: table_027
      - name: table_028
      - name: table_029
      - name: table_030
      - name: table_031
      - name: table_032
      - name: table_033
      - name: table_034
      - name: table_035
      - name: table_036
      - name: table_037
      - name: table_038
      - name: table_039
      - name: table_040
      - name: table_041
      - name: table_042
      - name: table_043
      - name: table_044
      - name: table_045
      - name: table_046
      - name: table_047
      - name: table_048
      - name: table_049
      - name: table_050
      - name: table_051
      - name: table_052
      - name: table_053
      - name: table_054
      - name: table_055
      - name: table_056
      - name: table_057
      - name: table_058
      - name: table_059
      - name: table_060
      - name: table_061
      - name: table_062
      - name: table_063
      - name: table_064
      - name: table_065
      - name: table_066
      - name: table_067
      - name: table_068
      - name: table_069
      - name: table_070
      - name: table_071
      - name: table_072
      - name: table_073
      - name: table_074
      - name: table_075
      - name: table_076
      - name: table_077
      - name: table_078
      - name: table_079
      - name: table_080
      - name: table_081
      - name: table_082
      - name: table_083
      - name: table_084
      - name: table_085
      - name: table_086
      - name: table_087
      - name: table_088
      - name: table_089
      - name: table_090
      - name: table_091
      - name: table_092
      - name: table_093
      - name: table_094
      - name: table_095
      - name: table_096
      - name: table_097
      - name: table_098
      - name: table_099
      - name: table_100